Config = {}

Config.SpawnDistance = 100.0
Config.DespawnDistance = 150.0
Config.UpdateInterval = 1000

Config.DefaultNPCSettings = {
    invincible = true,
    freeze = true,
    blockEvents = true,
    animDict = nil,
    animName = nil,
    scenario = nil,
    weapon = nil
}

Config.FavoritePeds = {
    'mp_m_freemode_01',
    'mp_f_freemode_01',
    's_m_y_cop_01',
    's_f_y_cop_01',
    's_m_m_paramedic_01',
    's_m_m_doctor_01',
    's_m_y_fireman_01',
    'a_m_y_business_01',
    'a_f_y_business_01',
    'a_m_m_farmer_01',
    'a_f_m_tourist_01',
    'a_m_y_hipster_01',
    'ig_bankman',
    'ig_barry',
    'ig_bestmen',
    'ig_beverly',
    'ig_car3guy1',
    'ig_chef',
    'ig_cletus',
    'ig_dale',
    'ig_davenport',
    'ig_denise',
    'ig_devin',
    'ig_dom',
    'ig_dreyfuss',
    'ig_fbisuit_01',
    'ig_floyd',
    'ig_groom',
    'ig_hao',
    'ig_hunter',
    'ig_janet',
    'ig_jay_norris',
    'ig_jewelass',
    'ig_jimmyboston',
    'ig_joeminuteman',
    'ig_johnnyklebitz',
    'ig_josef',
    'ig_josh',
    'ig_karen_daniels',
    'ig_kerrymcintosh',
    'ig_lifeinvad_01',
    'ig_lifeinvad_02',
    'ig_manuel',
    'ig_milton',
    'ig_mrk',
    'ig_natalia',
    'ig_nervousron',
    'ig_nigel',
    'ig_old_man1a',
    'ig_old_man2',
    'ig_omega',
    'ig_orleans',
    'ig_ortega',
    'ig_paper',
    'ig_priest',
    'ig_prolsec_02',
    'ig_ramp_gang',
    'ig_ramp_hic',
    'ig_ramp_hipster',
    'ig_ramp_mex',
    'ig_roccopelosi',
    'ig_russiandrunk',
    'ig_siemonyetarian',
    'ig_solomon',
    'ig_stevehains',
    'ig_stretch',
    'ig_talina',
    'ig_tanisha',
    'ig_terry',
    'ig_tomepsilon',
    'ig_tylerdix',
    'ig_wade',
    'ig_zimbor'
}